from flask import render_template, url_for, flash, redirect
from vendor_onboarding import app, db
from vendor_onboarding.forms import ContractorForm
from vendor_onboarding.models import Submission
from vendor_onboarding import os

import requests
import json

headers = {
    'Content-Type': "application/json",
    'QB-Realm-Hostname': os.getenv("QB_REALM"),
    'User-Agent': "api_chrome_test",
    'Authorization': os.getenv("QB_AUTH")
}


@app.route("/contractor", methods=['GET', 'POST'])
def vendor_form():
    form = ContractorForm()
    if form.validate_on_submit():

        if form.shipping_address_different.data == 'No':
            form.shipping_address.data = form.street_address.data
            form.shipping_address_2.data = form.street_address_2.data
            form.shipping_city.data = form.city.data
            form.shipping_state.data = form.state.data
            form.shipping_zip.data = form.zip.data

        if form.billing_address_different.data == 'No':
            form.billing_address.data = form.street_address.data
            form.billing_address_2.data = form.street_address_2.data
            form.billing_city.data = form.city.data
            form.billing_state.data = form.state.data
            form.billing_zip.data = form.zip.data

        form_data = {
            '6': {'value': str(form.company_name.data)},
            '7': {'value': str(form.street_address.data)},
            '8': {'value': str(form.street_address_2.data)},
            '9': {'value': str(form.city.data)},
            '10': {'value': str(form.state.data)},
            '11': {'value': str(form.zip.data)},
            '12': {'value': str(form.phone.data)},
            '14': {'value': str(form.website.data)},
            '15': {'value': str(form.shipping_address.data)},
            '16': {'value': str(form.shipping_address_2.data)},
            '17': {'value': str(form.shipping_city.data)},
            '18': {'value': str(form.shipping_state.data)},
            '19': {'value': str(form.shipping_zip.data)},
            '20': {'value': str(form.billing_address.data)},
            '21': {'value': str(form.billing_address_2.data)},
            '22': {'value': str(form.billing_city.data)},
            '23': {'value': str(form.billing_state.data)},
            '24': {'value': str(form.billing_zip.data)},
            '25': {'value': '{} {}'.format(str(form.p1_contact_first_name.data), str(form.p1_contact_last_name.data))},
            '26': {'value': str(form.p1_contact_title.data)},
            '27': {'value': str(form.p1_email.data)},
            '28': {'value': str(form.p1_work_phone.data)},
            '30': {'value': str(form.p1_mobile_phone.data)},
            '31': {'value': '{} {}'.format(str(form.p2_contact_first_name.data), str(form.p2_contact_last_name.data))},
            '32': {'value': str(form.p2_contact_title.data)},
            '33': {'value': str(form.p2_email.data)},
            '34': {'value': str(form.p2_work_phone.data)},
            '36': {'value': str(form.p2_mobile_phone.data)},
            '37': {'value': '{} {}'.format(str(form.ar_contact_first_name.data), str(form.ar_contact_last_name.data))},
            '38': {'value': str(form.ar_contact_title.data)},
            '39': {'value': str(form.ar_email.data)},
            '40': {'value': str(form.ar_work_phone.data)},
            '42': {'value': str(form.ar_mobile_phone.data)},
            '43': {'value': str(form.biz_date_started.data or '')},
            '44': {'value': str(form.biz_type.data)},
            '45': {'value': str(form.biz_ftin.data)},
            '46': {'value': str(form.biz_contractor_lic.data)},
            '47': {'value': str(form.biz_affiliate.data)},
            '48': {'value': str(form.biz_affiliate_company_name.data)},
            '49': {'value': str(form.biz_affiliate_address.data)},
            '50': {'value': str(form.biz_installer_cities.data)},
            '51': {'value': str(form.biz_disadvantaged.data)},
            '52': {'value': form.biz_disadvantaged_type_dobe.data},
            '53': {'value': form.biz_disadvantaged_type_dvbe.data},
            '54': {'value': form.biz_disadvantaged_type_mbe.data},
            '55': {'value': form.biz_disadvantaged_type_wbe.data},
            '56': {'value': str(form.biz_union.data)},
            '57': {'value': str(form.biz_union_name.data)},
            '58': {'value': form.biz_industries_served_commercial.data},
            '59': {'value': form.biz_industries_served_residential.data},
            '60': {'value': form.biz_industries_served_government.data},
            '61': {'value': form.biz_services_data.data},
            '62': {'value': form.biz_services_voice.data},
            '63': {'value': form.biz_services_fiber.data},
            '64': {'value': form.biz_services_security.data},
            '65': {'value': form.biz_services_electrical.data},
            '66': {'value': str(form.biz_services_other.data)},
            '67': {'value': str(form.biz_sub_electric.data)},
            '68': {'value': form.biz_tech_installed_routers.data},
            '69': {'value': form.biz_tech_installed_switches.data},
            '70': {'value': form.biz_tech_installed_servers.data},
            '71': {'value': form.biz_tech_installed_pbx.data},
            '72': {'value': form.biz_tech_installed_pos.data},
            '73': {'value': str(form.biz_tech_laptops.data)},
            '74': {'value': str(form.biz_tech_surveys.data)},
            '75': {'value': str(form.biz_tech_on_staff.data)},
            '76': {'value': form.biz_bicsi_rcdd.data or ''},
            '77': {'value': str(form.biz_testing_equipment.data)},
            '78': {'value': str(form.biz_data_voice_fiber_rate.data)},
            '79': {'value': str(form.biz_electrical_rate.data)},
            '80': {'value': str(form.biz_other.data)},
            '81': {'value': str(form.biz_coverage_area.data)},
            '82': {'value': str(form.biz_travel_without_charges.data)},
            '83': {'value': str(form.biz_travel_with_negotiations.data)},
            '84': {'value': form.biz_associations_bicsi.data},
            '85': {'value': form.biz_associations_comptia.data},
            '86': {'value': form.biz_associations_foa.data},
            '87': {'value': form.biz_associations_iscet.data},
            '88': {'value': form.biz_associations_neca.data},
            '89': {'value': form.biz_associations_pmi.data},
            '90': {'value': form.biz_associations_tpma.data},
            '91': {'value': form.biz_certifications_panduit.data},
            '92': {'value': form.biz_certifications_homaco.data},
            '93': {'value': form.biz_certifications_berk.data},
            '94': {'value': form.biz_certifications_amp.data},
            '95': {'value': form.biz_certifications_chatsworth.data},
            '96': {'value': form.biz_certifications_mowhawk.data},
            '97': {'value': form.biz_certifications_siemon.data},
            '98': {'value': form.biz_certifications_avaya.data},
            '99': {'value': form.biz_certifications_comm.data},
            '100': {'value': form.biz_certifications_ortronics.data},
            '101': {'value': form.biz_certifications_corning.data},
            '102': {'value': form.biz_certifications_belden.data},
            '103': {'value': form.biz_certifications_leviton.data},
            '104': {'value': form.biz_certifications_great.data},
            '105': {'value': form.biz_certifications_hoffman.data},
            '106': {'value': form.biz_certifications_hubbell.data},
            '107': {'value': form.biz_certifications_mod.data},
            '108': {'value': form.biz_certifications_superior.data},
            '109': {'value': str(form.ref_1_company_name.data)},
            '110': {'value': str(form.ref_1_desc.data)},
            '116': {'value': '{} {}'.format(str(form.ref_1_first_name.data), str(form.ref_1_last_name.data))},
            '117': {'value': str(form.ref_1_phone.data)},
            '118': {'value': str(form.ref_1_email.data)},
            '119': {'value': str(form.ref_1_contact.data)},
            '120': {'value': str(form.ref_2_company_name.data)},
            '121': {'value': str(form.ref_2_desc.data)},
            '122': {'value': '{} {}'.format(str(form.ref_2_first_name.data), str(form.ref_2_last_name.data))},
            '123': {'value': str(form.ref_2_phone.data)},
            '124': {'value': str(form.ref_2_email.data)},
            '125': {'value': str(form.ref_2_contact.data)},
            '126': {'value': str(form.biz_insurance.data)},
            '127': {'value': str(form.biz_limits.data)},
            '128': {'value': str(form.biz_aggregate.data)},
            '129': {'value': str(form.biz_limits_accident.data)},
            '130': {'value': str(form.biz_workers_comp.data)},
            '131': {'value': str(form.biz_disease.data)},
            '132': {'value': str(form.biz_disease_each_employee.data)},
            '138': {'value': str(form.biz_lang.data)},
            '145': {'value': str(form.biz_affiliate_street_address_2.data)},
            '146': {'value': str(form.biz_affiliate_city.data)},
            '147': {'value': str(form.biz_affiliate_state.data)},
            '148': {'value': str(form.biz_affiliate_zip.data)},
            '149': {'value': form.biz_services_wap.data},
            '150': {'value': form.biz_services_it.data},
            '151': {'value': form.biz_services_pos.data},
            '152': {'value': form.biz_services_iot.data},
            '153': {'value': str(form.biz_tech_installed_other.data)},
            '162': {'value': form.biz_tech_installed_av.data},
            '163': {'value': form.biz_tech_installed_cctv.data},
            '164': {'value': form.biz_tech_installed_cisco_colab.data},
            '165': {'value': form.biz_tech_installed_video_conf.data},
            '166': {'value': form.biz_tech_installed_server.data},
            '167': {'value': form.biz_tech_installed_pc.data},
            '168': {'value': form.biz_tech_installed_netapp.data},
            '169': {'value': form.biz_tech_installed_vlan.data},
            '170': {'value': form.biz_tech_installed_gpon.data},
            '171': {'value': form.biz_tech_installed_ekahau.data},
            '172': {'value': form.biz_tech_installed_switch.data},
            '173': {'value': form.biz_tech_installed_docsis.data}
        }

        json_payload = {
            'to': os.getenv('QB_TABLE'),
            'data': [form_data]
        }

        r = requests.post(os.getenv('QB_API'), headers=headers, json=json_payload)
        response = r.json()

        submission = Submission(company_name=form.company_name.data,
                                street_address=form.street_address.data,
                                street_address_2=form.street_address_2.data,
                                city=form.city.data,
                                state=form.state.data,
                                zip=form.zip.data,
                                phone=form.phone.data,
                                website=form.website.data,
                                shipping_address=form.shipping_address.data,
                                shipping_address_2=form.shipping_address_2.data,
                                shipping_city=form.shipping_city.data,
                                shipping_state=form.shipping_state.data,
                                shipping_zip=form.shipping_zip.data,
                                billing_address=form.billing_address.data,
                                billing_address_2=form.billing_address_2.data,
                                billing_city=form.billing_city.data,
                                billing_state=form.billing_state.data,
                                billing_zip=form.billing_zip.data,
                                p1_contact_first_name=form.p1_contact_first_name.data,
                                p1_contact_last_name=form.p1_contact_last_name.data,
                                p1_contact_title=form.p1_contact_title.data,
                                p1_email=form.p1_email.data,
                                p1_work_phone=form.p1_work_phone.data,
                                p1_mobile_phone=form.p1_mobile_phone.data,
                                p2_contact_first_name=form.p2_contact_first_name.data,
                                p2_contact_last_name=form.p2_contact_last_name.data,
                                p2_contact_title=form.p2_contact_title.data,
                                p2_email=form.p2_email.data,
                                p2_work_phone=form.p2_work_phone.data,
                                p2_mobile_phone=form.p2_mobile_phone.data,
                                ar_contact_first_name=form.ar_contact_first_name.data,
                                ar_contact_last_name=form.ar_contact_last_name.data,
                                ar_contact_title=form.ar_contact_title.data,
                                ar_email=form.ar_email.data,
                                ar_work_phone=form.ar_work_phone.data,
                                ar_mobile_phone=form.ar_mobile_phone.data,
                                biz_date_started=form.biz_date_started.data,
                                biz_type=form.biz_type.data,
                                biz_contractor_lic=form.biz_contractor_lic.data,
                                biz_ftin=form.biz_ftin.data,
                                biz_affiliate=form.biz_affiliate.data,
                                biz_affiliate_company_name=form.biz_affiliate_company_name.data,
                                biz_affiliate_address=form.biz_affiliate_address.data,
                                biz_affiliate_street_address_2=form.biz_affiliate_street_address_2.data,
                                biz_affiliate_city=form.biz_affiliate_city.data,
                                biz_affiliate_state=form.biz_affiliate_state.data,
                                biz_affiliate_zip=form.biz_affiliate_zip.data,
                                biz_installer_cities=form.biz_installer_cities.data,
                                biz_disadvantaged=form.biz_disadvantaged.data,
                                biz_disadvantaged_type_dobe=form.biz_disadvantaged_type_dobe.data,
                                biz_disadvantaged_type_dvbe=form.biz_disadvantaged_type_dvbe.data,
                                biz_disadvantaged_type_mbe=form.biz_disadvantaged_type_mbe.data,
                                biz_disadvantaged_type_wbe=form.biz_disadvantaged_type_wbe.data,
                                biz_lang=form.biz_lang.data,
                                biz_union=form.biz_union.data,
                                biz_union_name=form.biz_union_name.data,
                                biz_industries_served_commercial=form.biz_industries_served_commercial.data,
                                biz_industries_served_residential=form.biz_industries_served_residential.data,
                                biz_industries_served_government=form.biz_industries_served_government.data,
                                biz_services_data=form.biz_services_data.data,
                                biz_services_voice=form.biz_services_voice.data,
                                biz_services_fiber=form.biz_services_fiber.data,
                                biz_services_security=form.biz_services_security.data,
                                biz_services_electrical=form.biz_services_electrical.data,
                                biz_services_wap=form.biz_services_wap.data,
                                biz_services_it=form.biz_services_it.data,
                                biz_services_pos=form.biz_services_pos.data,
                                biz_services_iot=form.biz_services_iot.data,
                                biz_services_other=form.biz_services_other.data,
                                biz_sub_electric=form.biz_sub_electric.data,
                                biz_tech_installed_routers=form.biz_tech_installed_routers.data,
                                biz_tech_installed_switches=form.biz_tech_installed_switches.data,
                                biz_tech_installed_servers=form.biz_tech_installed_servers.data,
                                biz_tech_installed_pbx=form.biz_tech_installed_pbx.data,
                                biz_tech_installed_pos=form.biz_tech_installed_pos.data,
                                biz_tech_installed_waps=form.biz_tech_installed_waps.data,
                                biz_tech_installed_av=form.biz_tech_installed_av.data,
                                biz_tech_installed_cctv=form.biz_tech_installed_cctv.data,
                                biz_tech_installed_cisco_colab=form.biz_tech_installed_cisco_colab.data,
                                biz_tech_installed_video_conf=form.biz_tech_installed_video_conf.data,
                                biz_tech_installed_server=form.biz_tech_installed_server.data,
                                biz_tech_installed_pc=form.biz_tech_installed_pc.data,
                                biz_tech_installed_netapp=form.biz_tech_installed_netapp.data,
                                biz_tech_installed_vlan=form.biz_tech_installed_vlan.data,
                                biz_tech_installed_gpon=form.biz_tech_installed_gpon.data,
                                biz_tech_installed_ekahau=form.biz_tech_installed_ekahau.data,
                                biz_tech_installed_switch=form.biz_tech_installed_switch.data,
                                biz_tech_installed_docsis=form.biz_tech_installed_docsis.data,
                                biz_tech_installed_other=form.biz_tech_installed_other.data,
                                biz_tech_laptops=form.biz_tech_laptops.data,
                                biz_tech_surveys=form.biz_tech_surveys.data,
                                biz_tech_on_staff=form.biz_tech_on_staff.data,
                                biz_bicsi_rcdd=form.biz_bicsi_rcdd.data,
                                biz_testing_equipment=form.biz_testing_equipment.data,
                                biz_data_voice_fiber_rate=form.biz_data_voice_fiber_rate.data,
                                biz_electrical_rate=form.biz_electrical_rate.data,
                                biz_other=form.biz_other.data,
                                biz_coverage_area=form.biz_coverage_area.data,
                                biz_travel_without_charges=form.biz_travel_without_charges.data,
                                biz_travel_with_negotiations=form.biz_travel_with_negotiations.data,
                                biz_associations_bicsi=form.biz_associations_bicsi.data,
                                biz_associations_comptia=form.biz_associations_comptia.data,
                                biz_associations_foa=form.biz_associations_foa.data,
                                biz_associations_iscet=form.biz_associations_iscet.data,
                                biz_associations_neca=form.biz_associations_neca.data,
                                biz_associations_pmi=form.biz_associations_pmi.data,
                                biz_associations_tpma=form.biz_associations_tpma.data,
                                biz_certifications_panduit=form.biz_certifications_panduit.data,
                                biz_certifications_homaco=form.biz_certifications_homaco.data,
                                biz_certifications_berk=form.biz_certifications_berk.data,
                                biz_certifications_amp=form.biz_certifications_amp.data,
                                biz_certifications_chatsworth=form.biz_certifications_chatsworth.data,
                                biz_certifications_mowhawk=form.biz_certifications_mowhawk.data,
                                biz_certifications_siemon=form.biz_certifications_siemon.data,
                                biz_certifications_avaya=form.biz_certifications_avaya.data,
                                biz_certifications_comm=form.biz_certifications_comm.data,
                                biz_certifications_ortronics=form.biz_certifications_ortronics.data,
                                biz_certifications_corning=form.biz_certifications_corning.data,
                                biz_certifications_belden=form.biz_certifications_belden.data,
                                biz_certifications_leviton=form.biz_certifications_leviton.data,
                                biz_certifications_great=form.biz_certifications_great.data,
                                biz_certifications_hoffman=form.biz_certifications_hoffman.data,
                                biz_certifications_hubbell=form.biz_certifications_hubbell.data,
                                biz_certifications_mod=form.biz_certifications_mod.data,
                                biz_certifications_superior=form.biz_certifications_superior.data,
                                ref_1_company_name=form.ref_1_company_name.data,
                                ref_1_desc=form.ref_1_desc.data,
                                ref_1_first_name=form.ref_1_first_name.data,
                                ref_1_last_name=form.ref_1_last_name.data,
                                ref_1_phone=form.ref_1_phone.data,
                                ref_1_email=form.ref_1_email.data,
                                ref_1_contact=form.ref_1_contact.data,
                                ref_2_company_name=form.ref_2_company_name.data,
                                ref_2_desc=form.ref_2_desc.data,
                                ref_2_first_name=form.ref_2_first_name.data,
                                ref_2_last_name=form.ref_2_last_name.data,
                                ref_2_phone=form.ref_2_phone.data,
                                ref_2_email=form.ref_2_email.data,
                                ref_2_contact=form.ref_2_contact.data,
                                biz_insurance=form.biz_insurance.data,
                                biz_limits=form.biz_limits.data,
                                biz_aggregate=form.biz_aggregate.data,
                                biz_workers_comp=form.biz_workers_comp.data,
                                biz_limits_accident=form.biz_limits_accident.data,
                                biz_disease=form.biz_disease.data,
                                biz_disease_each_employee=form.biz_disease_each_employee.data,
                                form_payload=json_payload,
                                qb_response=r.json())
        db.session.add(submission)
        db.session.commit()

        flash(
            f'Thank you! Your submission for {form.company_name.data} has been successfully processed',
            'success')
        return redirect(url_for('vendor_form'))
    return render_template('vendor_form.html', title='Contractor Application', page_name='Contractor Application',
                           form=form)


if __name__ == '__main__':
    app.run(debug=True)
